package suzaku.ui.style

import scala.language.implicitConversions

sealed trait RGBColor {
  val rgb: Int
  def r: Int = (rgb >> 16) & 0xFF
  def g: Int = (rgb >> 8) & 0xFF
  def b: Int = rgb & 0xFF
}

case class RGB(rgb: Int) extends RGBColor

case class RGBA(rgb: Int, a: Double) extends RGBColor

trait Colors {
  @inline def rgb(r: Int, g: Int, b: Int) = RGB(((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF))

  @inline def rgba(r: Int, g: Int, b: Int, a: Double) = RGBA(((r & 0xFF) << 16) | ((g & 0xFF) << 8) | (b & 0xFF), a)

  implicit def int2color(i: Int): RGB = RGB(i & 0xFFFFFF)
}

object Colors {
  val aliceblue            = RGB(0xF0F8FF)
  val antiquewhite         = RGB(0xFAEBD7)
  val aqua                 = RGB(0x00FFFF)
  val aquamarine           = RGB(0x7FFFD4)
  val azure                = RGB(0xF0FFFF)
  val beige                = RGB(0xF5F5DC)
  val bisque               = RGB(0xFFE4C4)
  val black                = RGB(0x000000)
  val blanchedalmond       = RGB(0xFFEBCD)
  val blue                 = RGB(0x0000FF)
  val blueviolet           = RGB(0x8A2BE2)
  val brown                = RGB(0xA52A2A)
  val burlywood            = RGB(0xDEB887)
  val cadetblue            = RGB(0x5F9EA0)
  val chartreuse           = RGB(0x7FFF00)
  val chocolate            = RGB(0xD2691E)
  val coral                = RGB(0xFF7F50)
  val cornflowerblue       = RGB(0x6495ED)
  val cornsilk             = RGB(0xFFF8DC)
  val crimson              = RGB(0xDC143C)
  val cyan                 = RGB(0x00FFFF)
  val darkblue             = RGB(0x00008B)
  val darkcyan             = RGB(0x008B8B)
  val darkgoldenrod        = RGB(0xB8860B)
  val darkgray             = RGB(0xA9A9A9)
  val darkgreen            = RGB(0x006400)
  val darkkhaki            = RGB(0xBDB76B)
  val darkmagenta          = RGB(0x8B008B)
  val darkolivegreen       = RGB(0x556B2F)
  val darkorange           = RGB(0xFF8C00)
  val darkorchid           = RGB(0x9932CC)
  val darkred              = RGB(0x8B0000)
  val darksalmon           = RGB(0xE9967A)
  val darkseagreen         = RGB(0x8FBC8F)
  val darkslateblue        = RGB(0x483D8B)
  val darkslategray        = RGB(0x2F4F4F)
  val darkturquoise        = RGB(0x00CED1)
  val darkviolet           = RGB(0x9400D3)
  val deeppink             = RGB(0xFF1493)
  val deepskyblue          = RGB(0x00BFFF)
  val dimgray              = RGB(0x696969)
  val dodgerblue           = RGB(0x1E90FF)
  val firebrick            = RGB(0xB22222)
  val floralwhite          = RGB(0xFFFAF0)
  val forestgreen          = RGB(0x228B22)
  val fuchsia              = RGB(0xFF00FF)
  val gainsboro            = RGB(0xDCDCDC)
  val ghostwhite           = RGB(0xF8F8FF)
  val gold                 = RGB(0xFFD700)
  val goldenrod            = RGB(0xDAA520)
  val gray                 = RGB(0x7F7F7F)
  val green                = RGB(0x008000)
  val greenyellow          = RGB(0xADFF2F)
  val honeydew             = RGB(0xF0FFF0)
  val hotpink              = RGB(0xFF69B4)
  val indianred            = RGB(0xCD5C5C)
  val indigo               = RGB(0x4B0082)
  val ivory                = RGB(0xFFFFF0)
  val khaki                = RGB(0xF0E68C)
  val lavender             = RGB(0xE6E6FA)
  val lavenderblush        = RGB(0xFFF0F5)
  val lawngreen            = RGB(0x7CFC00)
  val lemonchiffon         = RGB(0xFFFACD)
  val lightblue            = RGB(0xADD8E6)
  val lightcoral           = RGB(0xF08080)
  val lightcyan            = RGB(0xE0FFFF)
  val lightgoldenrodyellow = RGB(0xFAFAD2)
  val lightgreen           = RGB(0x90EE90)
  val lightgrey            = RGB(0xD3D3D3)
  val lightpink            = RGB(0xFFB6C1)
  val lightsalmon          = RGB(0xFFA07A)
  val lightseagreen        = RGB(0x20B2AA)
  val lightskyblue         = RGB(0x87CEFA)
  val lightslategray       = RGB(0x778899)
  val lightsteelblue       = RGB(0xB0C4DE)
  val lightyellow          = RGB(0xFFFFE0)
  val lime                 = RGB(0x00FF00)
  val limegreen            = RGB(0x32CD32)
  val linen                = RGB(0xFAF0E6)
  val magenta              = RGB(0xFF00FF)
  val maroon               = RGB(0x800000)
  val mediumaquamarine     = RGB(0x66CDAA)
  val mediumblue           = RGB(0x0000CD)
  val mediumorchid         = RGB(0xBA55D3)
  val mediumpurple         = RGB(0x9370DB)
  val mediumseagreen       = RGB(0x3CB371)
  val mediumslateblue      = RGB(0x7B68EE)
  val mediumspringgreen    = RGB(0x00FA9A)
  val mediumturquoise      = RGB(0x48D1CC)
  val mediumvioletred      = RGB(0xC71585)
  val midnightblue         = RGB(0x191970)
  val mintcream            = RGB(0xF5FFFA)
  val mistyrose            = RGB(0xFFE4E1)
  val moccasin             = RGB(0xFFE4B5)
  val navajowhite          = RGB(0xFFDEAD)
  val navy                 = RGB(0x000080)
  val navyblue             = RGB(0x9FAFDF)
  val oldlace              = RGB(0xFDF5E6)
  val olive                = RGB(0x808000)
  val olivedrab            = RGB(0x6B8E23)
  val orange               = RGB(0xFFA500)
  val orangered            = RGB(0xFF4500)
  val orchid               = RGB(0xDA70D6)
  val palegoldenrod        = RGB(0xEEE8AA)
  val palegreen            = RGB(0x98FB98)
  val paleturquoise        = RGB(0xAFEEEE)
  val palevioletred        = RGB(0xDB7093)
  val papayawhip           = RGB(0xFFEFD5)
  val peachpuff            = RGB(0xFFDAB9)
  val peru                 = RGB(0xCD853F)
  val pink                 = RGB(0xFFC0CB)
  val plum                 = RGB(0xDDA0DD)
  val powderblue           = RGB(0xB0E0E6)
  val purple               = RGB(0x800080)
  val red                  = RGB(0xFF0000)
  val rosybrown            = RGB(0xBC8F8F)
  val royalblue            = RGB(0x4169E1)
  val saddlebrown          = RGB(0x8B4513)
  val salmon               = RGB(0xFA8072)
  val sandybrown           = RGB(0xFA8072)
  val seagreen             = RGB(0x2E8B57)
  val seashell             = RGB(0xFFF5EE)
  val sienna               = RGB(0xA0522D)
  val silver               = RGB(0xC0C0C0)
  val skyblue              = RGB(0x87CEEB)
  val slateblue            = RGB(0x6A5ACD)
  val slategray            = RGB(0x708090)
  val snow                 = RGB(0xFFFAFA)
  val springgreen          = RGB(0x00FF7F)
  val steelblue            = RGB(0x4682B4)
  val tan                  = RGB(0xD2B48C)
  val teal                 = RGB(0x008080)
  val thistle              = RGB(0xD8BFD8)
  val tomato               = RGB(0xFF6347)
  val turquoise            = RGB(0x40E0D0)
  val violet               = RGB(0xEE82EE)
  val wheat                = RGB(0xF5DEB3)
  val white                = RGB(0xFFFFFF)
  val whitesmoke           = RGB(0xF5F5F5)
  val yellow               = RGB(0xFFFF00)
  val yellowgreen          = RGB(0x9ACD32)
}
